# Generated by Django 4.1.1 on 2022-09-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='produk',
            fields=[
                ('idproduk', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jumlahstok', models.IntegerField()),
                ('namaproduk', models.CharField(max_length=100)),
                ('satuanproduk', models.CharField(max_length=10)),
                ('hargaproduk', models.IntegerField()),
                ('kategoriproduk', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='idkaryawan',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='idpembelian',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('idpenjualan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tanggalpenjualan', models.DateField()),
                ('namapelanggan', models.CharField(max_length=100)),
                ('idkaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='detailpenjualan',
            fields=[
                ('iddetailpenjualan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kuantitasproduk', models.IntegerField()),
                ('idpenjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjualan')),
                ('idproduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk')),
            ],
        ),
        migrations.CreateModel(
            name='detailpembelian',
            fields=[
                ('iddetailpembelian', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kuantitasproduk', models.IntegerField()),
                ('idpembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembelian')),
                ('idproduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk')),
            ],
        ),
    ]
